onlyBuiltDependencies:
  - '@nestjs/core'
  - '@parcel/watcher'
  - '@prisma/engines'
  - '@scarf/scarf'
  - '@swc/core'
  - bcrypt
  - core-js-pure
  - esbuild
  - less
  - lmdb
  - msgpackr-extract
  - nx
  - prisma
  - sharp
  - unrs-resolver
