import { withMutations, withResource } from '@angular-architects/ngrx-toolkit';
import { httpResource } from '@angular/common/http';
import { computed, inject } from '@angular/core';
import {
  patchState,
  signalStoreFeature,
  SignalStoreFeature,
  withComputed,
  withHooks,
  withMethods,
  withState,
} from '@ngrx/signals';
import { TranslateService } from '@ngx-translate/core';
import { DictionaryApiService, type DictionariesResponse } from 'libs/frontend/features/dictionary-old';
import { getDictionaryHelper } from './dictionaries.helpers';

/**
 * Feature that manages dictionaries loaded from API
 * Uses withResource for automatic state management with named resources (loading, error, value)
 */
export function withDictionariesFeatures(): SignalStoreFeature {
  return signalStoreFeature(
    withState(() => ({
      selectedLanguage: '' as string,
    })),
    withResource(
      (store, dictionaryApi = inject(DictionaryApiService)) => ({
        dictionaries: httpResource<DictionariesResponse>( // dictionaries is the prefix for generated state and methods
          () => dictionaryApi.dictionariesUrl().toString(),
          {
            defaultValue: { dictionaries: {}, languages: [] },
          }
        ),
      }),
      { errorHandling: 'previous value' }
    ),
    withMutations((store) => ({
      // A completer mutation to save dictionaries if needed in the future
      // saveDictionaries: store._dictionariesService.createSaveMutation({
      //   onSuccess(dictionaries: DictionariesResponse) {
      //     console.log('✅ Dictionaries saved successfully:', dictionaries);
      //     // Optionally update the resource state
      //     patchState(store, {
      //       dictionaries: dictionaries,
      //     });
      //   },
      //   onError(error: any) {
      //     console.error('❌ Error saving dictionaries:', error);
      //   },
      // }),
    })),

    withMethods(
      (
        store,
        translateService = inject(TranslateService)
      ) => {
        return {
          /**
           * Load all dictionaries from API
           * Uses _dictionariesReload() generated by withResource
           */
          loadDictionaries: () => {
            const success = store._dictionariesReload();
            if (success) {
              console.log('🔄 Dictionaries reload triggered');
            }
          },

          /**
           * Change to next language in the list
           */
          changeLanguage: () => {
            const dictionaries = store.dictionariesValue()?.dictionaries ?? {};
            const languages = Object.keys(dictionaries);
            if (languages.length === 0) return;

            const currentIndex = languages.indexOf(store.selectedLanguage());
            const nextIndex = (currentIndex + 1) % languages.length;
            const nextLanguage = languages[nextIndex];

            patchState(store, { selectedLanguage: nextLanguage });
            translateService.use(nextLanguage);
            console.log(`🌐 Language changed to: ${nextLanguage}`);
          },

          /**
           * Switch to a specific language
           */
          switchLanguage: (language: string) => {
            patchState(store, { selectedLanguage: language });
            translateService.use(language);
            console.log(`🌐 Language switched to: ${language}`);
          },

          /**
           * Reset dictionaries to initial state (called on logout)
           */
          resetDictionaries: () => {
            patchState(store, {
              selectedLanguage: '',
            });
            // Note: withResource state is managed automatically, no manual reset needed
            console.log(`🔄 Dictionaries reset to initial state`);
          },
        };
      }
    ),
    withComputed((store) => {
      return {
        selectedDictionary: computed(() =>
          getDictionaryHelper(store.selectedLanguage(), store.dictionariesValue()?.dictionaries ?? {})
        ),
      };
    }),
    withHooks((store, translateService = inject(TranslateService)) => ({
      onInit: () => {
        // Load dictionaries from API using withResource
        store.loadDictionaries();

        // Set browser language as default
        const browserLang = translateService.getBrowserLang() || 'en';
        translateService.use(browserLang);

        patchState(store, { selectedLanguage: browserLang });

        console.log(`🌐 Detected Browser Language: ${browserLang}`);
        console.log(`🌐 Current Language on init: ${browserLang}`);
      },
    }))
  );
}
